# WARNING: Do not edit this file.
# It was generated by processing /Users/ali/.config/yadm/alt/.config/zsh/.zshrc##t.default

### Set XDG Paths ###
export XDG_CONFIG_HOME=/Users/ali/.config
export XDG_CACHE_HOME=/Users/ali/.cache
export XDG_DATA_HOME=/Users/ali/.local/share
export XDG_RUNTIME_DIR=/run/user/$UID
export XDG_STATE_HOME=/Users/ali/.local/state
export XDG_DATA_DIRS=/usr/local/share/:/usr/share/
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_DESKTOP_DIR="/Users/ali/Desktop"
export XDG_DOCUMENTS_DIR="/Users/ali/Documents"
export XDG_DOWNLOAD_DIR="/Users/ali/Downloads"
export XDG_MUSIC_DIR="/Users/ali/Music"
export XDG_PICTURES_DIR="/Users/ali/Pictures"
export XDG_PUBLICSHARE_DIR="/Users/ali/Public"
export XDG_TEMPLATES_DIR="/Users/ali/Templates"
export XDG_VIDEOS_DIR="/Users/ali/Videos"
### End XDG ###

### Configure fzf ###
export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#b4befe,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
--color=selected-bg:#45475a \
--color=border:#313244,label:#cdd6f4"

export FZF_BASE=/opt/homebrew/bin
### End fzf ###

### Configure Homebrew ###
export HOMEBREW_BUNDLE_FILE=${XDG_CONFIG_HOME}/brewfile/Brewfile ### Set Brewfile
export PATH=/opt/homebrew/bin:$PATH
### End Homebrew ###

export STARSHIP_CONFIG=$XDG_CONFIG_HOME/starship/starship.toml

# The following lines were added by compinstall
zstyle :compinstall filename "${ZDOTDIR}/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall

### Set up pyenv ###
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"
### End pyenv ###

### Configure zoxide ###
export _ZO_DATA_DIR=${XDG_DATA_HOME}
export ZOXIDE_CMD_OVERRIDE=cd
### End zoxide ###

source ${ZDOTDIR}/configs/sheldon
