shell = "zsh"
apply = ["source"]

[plugins.starship]
github = "axieax/zsh-starship"

[plugins.bat]
github = "fdellwing/zsh-bat"

[plugins.fzf-git]
github = "junegunn/fzf-git.sh"

[plugins.fzf]
remote = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/fzf/fzf.plugin.zsh"

[plugins.git]
remote = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/git/git.plugin.zsh"

[plugins.pyenv]
remote = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/pyenv/pyenv.plugin.zsh"

[plugins.aws]
remote = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/aws/aws.plugin.zsh"
profiles = ["Work"]

[plugins.zoxide]
remote = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/zoxide/zoxide.plugin.zsh"
